### ISSUE TITLE
请问在更下游任务上有使用过多任务训练的结果fine tune吗

### ISSUE THREAD

**Issue by freefuiiismyname** [JayYip/m3tl#11]
RT

**Comment by JayYip** [comment]
没有尝试过, 我目前就这几个任务, 都一起做了

**Comment by freefuiiismyname** [comment]
谢谢你的回复。:)
基于你的训练结果，我有意在机器阅读理解上尝试fine tune(如果允许的话)。不过，有一点想请教的是，你训练了多少个step，batch size和文本长度是多少呢？

**Comment by JayYip** [comment]
我训练了30个epochs, batch_size和max_seq_len分别是32和128, 我用的是Titan Xp, 如果你的显存比较大的话可以加大batch_size.

**Comment by freefuiiismyname** [comment]
seq_len太小了，看来不适合做阅读理解啦。
谢谢你的解答~！

**Comment by haoyuhu** [comment]
> seq_len太小了，看来不适合做阅读理解啦。
> 谢谢你的解答~！

感觉长文本理解得话BERT不如LSTM
