### ISSUE TITLE
Performance issue in m3tl/read_write_tfrecord.py

### ISSUE THREAD

**Issue by DLPerf** [JayYip/m3tl#115]
Hello! Our static bug checker has found a performance issue in m3tl/read_write_tfrecord.py:  [`reshape_tensors_in_dataset`](https://github.com/JayYip/m3tl/blob/a948cc90017ec03b00a3496bab742e0ad8887952/m3tl/read_write_tfrecord.py#L529) is repeatedly called in a for loop, but there is a tf.function decorated function [`_reshape_tensor`](https://github.com/JayYip/m3tl/blob/a948cc90017ec03b00a3496bab742e0ad8887952/m3tl/read_write_tfrecord.py#L365) defined and called in  [`reshape_tensors_in_dataset`](https://github.com/JayYip/m3tl/blob/a948cc90017ec03b00a3496bab742e0ad8887952/m3tl/read_write_tfrecord.py#L351). 

In that case, when `reshape_tensors_in_dataset` is called in a loop, the function `_reshape_tensor` will create a new graph every time, and that can trigger tf.function retracing warning.

Here is [the tensorflow document](https://tensorflow.google.cn/guide/function#tracing) to support it.

Briefly, for better efficiency, it's better to use:
```python
@tf.function
def inner():
    pass

def outer():
    inner()  
```
than:
```python
def outer():
    @tf.function
    def inner():
        pass
    inner()
```

Looking forward to your reply.

**Comment by JayYip** [comment]
Hi,

Thanks for the update. Please create a PR to fix this issue.
