### ISSUE TITLE
global step double increment

### ISSUE THREAD

**Issue by gbuion** [JayYip/m3tl#12]
https://github.com/JayYip/bert-multitask-learning/blob/9f6950eb72a98e877558701d4ade9aec9ba76bc9/src/model_fn.py#L326

optimizer.apply_gradients() will increase global step once when param global_step is not set to None. So in this line, global step will be increased again which it doesn't make sense. The issue can influence the number of train step when using max_steps or steps parameter in estimator.train()

BTW, thanks for sharing the optimization implementation for BERT multi-gpu.

Reference: https://github.com/tensorflow/tensorflow/blob/743dea5427b11ff08782f4c352b8424aa7fad982/tensorflow/python/training/optimizer.py#L546

**Comment by JayYip** [comment]
Yes. This is a bug. Thanks.
