### ISSUE TITLE
muti-task classifiction

### ISSUE THREAD

**Issue by chiyuzhang94** [JayYip/m3tl#15]
Hi, thanks for your great jobs! I am wondering if I can use it for multi-task classifications.

**Comment by JayYip** [comment]
You sure can!

Just implement the preprocessing function. You can refer to [this notebook](https://github.com/JayYip/bert-multitask-learning/blob/master/notebooks/Run%20Self%20Defined%20Problem.ipynb) for implementation details.

Then you can do something like:
```python
@preprocessing_fn
def problem_a(params, mode):
    # read data
    return input_list, target_list

@preprocessing_fn
def problem_b(params, mode):
    # read data
    return input_list, target_list

new_problem_type = {'problem_a': 'cls', 'problem_b': 'cls'}
new_problem_process_fn_dict = {'problem_a': problem_a, 'problem_b': problem_b}

params = DynamicBatchSizeParams()
params.init_checkpoint = 'models/cased_L-12_H-768_A-12'

train_bert_multitask(problem='problem_a|problem_b', num_gpus=1, 
                     num_epochs=10, params=params, 
                     problem_type_dict=new_problem_type, processing_fn_dict=new_problem_process_fn_dict)
```

**Comment by chiyuzhang94** [comment]
Thanks for your reply. I am trying to use the example on my Macbook. But I cannot install the package. I got this error ` ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.13.1 (from bert_multitask_learning) (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0)
ERROR: No matching distribution found for tensorflow-gpu==1.13.1 (from bert_multitask_learning)`

My python version is Python 3.6.5. I cannot use tensorflow gpu because of the macbook. How should I install it?

**Comment by JayYip** [comment]
Sorry, I have never try installing tensorflow-gpu on a Mac. You can install tensorflow-gpu separately and try installing the package again. I don't have a Mac with GPU so there's little thing I can do to help.

**Comment by chiyuzhang94** [comment]
I tried install in my Linux system but give me this error 
`Command "/home/py3.6/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-j_u_62gy/pyarrow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-9mymnqgn/install-record.txt --single-version-externally-managed --compile --install-headers /home/py3.6/include/site/python3.6/pyarrow" failed with error code 1 in /tmp/pip-install-j_u_62gy/pyarrow/`

**Comment by JayYip** [comment]
Is the pyarrow successfully installed?

**Comment by chiyuzhang94** [comment]
Yes, I installed pyarrow. But I also have some other environment issues.
