### ISSUE TITLE
Why so great architectural changes?

### ISSUE THREAD

**Issue by ohwe** [JayYip/m3tl#2]
Hi! Great to see such a tremendous work done. One question: why do you consider such great changes to the project architecture necessary? Why just passing DistributionStrategy to estimator would not be enough? And did you try Horovod from Uber for the same purpose?

**Comment by JayYip** [comment]
> why do you consider such great changes to the project architecture necessary? Why just passing DistributionStrategy to estimator would not be enough?

Hi, this repo is extracted from an private project that I am working at. So to me, it's more like I adapted BERT to my architecture. Plus, like I mentioned in README.md, the original purpose of this repo is not multi-GPU version of BERT, it's multitask learning. In the original BERT repo, data preprocessing, task specific classification layers are separated into several files, which makes multitask learning not possible. You can use this repo if you:

1. Need multi-task learning
2. Need multiple GPU training
3. Need Sequence labeling 

> And did you try Horovod from Uber for the same purpose?

And no. Horovod is more general. For now, I only want to try out BERT on different tasks. 

If you have any difficulties adding your own problems or spot any bugs, please feel free to contact me or open an issue. 

I will close this issue for now but please feel free to reopen it. 

Cheers!

**Comment by guotong1988** [comment]
thx
