### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by ZTurboX** [JayYip/m3tl#24]
请问notebook中，分类的例子中，这里params.init_checkpoint = 'models/cased_L-12_H-768_A-12'是原始bert的模型吗？还有这个项目有模型说明吗或者论文？谢谢

**Comment by JayYip** [comment]
> params.init_checkpoint = 'models/cased_L-12_H-768_A-12'是原始bert的模型吗？

是的

> 这个项目有模型说明吗或者论文？

目前没有, 因为模型比较简单, 类似于微软的MT-DNN

**Comment by ZTurboX** [comment]
那么这个文本分类，是哪些任务一起做的？哪里体现是multi-task?

**Comment by JayYip** [comment]
在该例子里面并没有其他任务, 是single task

**Comment by ZTurboX** [comment]
那么用这个代码怎样做mutli-task的文本分类

**Comment by JayYip** [comment]
你定义好problem的预处理函数，然后训练的problem参数设置为“problem_a|problem_b”

**Comment by ZTurboX** [comment]
这个只能在gpu上运行吗？

**Comment by JayYip** [comment]
你可以稍微修改一下执行函数, 但是在cpu上运行会比较慢.

[这里](https://github.com/JayYip/bert-multitask-learning/blob/9fe97739194f801e539efbadbaaf97a9c945eaaa/bert_multitask_learning/run_bert_multitask.py#L26)应该会要求`num_gpu`大于0.

**Comment by ZTurboX** [comment]
但是我用gpu运行总是报这个错
![image](https://user-images.githubusercontent.com/5669444/63836826-e8df0a80-c9ac-11e9-9603-424361cd823f.png)

**Comment by JayYip** [comment]
你看`Registered devices`那里没有GPU

**Comment by ZTurboX** [comment]
可是代码直接用的你的例子的代码

**Comment by JayYip** [comment]
这应该不是这个代码问题, 有可能是你的驱动, 有可能是TF的版本, 有可能是`CUDA_VISIBLE_DEVICES `参数的设置
