### ISSUE TITLE
How to add vocab

### ISSUE THREAD

**Issue by cszer** [JayYip/m3tl#26]
Hello,thank you for this great implementation.I want to use different vocab and init checkpoint.But in DynamicBatchSizeParams() methods there is only 'decode_vocab_file' method.Is it about adding vocab?

**Comment by JayYip** [comment]
Hi, the vocabulary table comes with the initial checkpoint (official bert
checkpoint). So you can change that directly.

**Comment by cszer** [comment]
thanks,i am trying to train custom ner on english,i have written my own preprocessing,but need i create function like NER in ner_data.py or i shold only create preprocessing?

**Comment by cszer** [comment]
i have already done it,yahoo! If you want i can add to master my function to train on medcine english data.
