### ISSUE TITLE
Example for Pre-training

### ISSUE THREAD

**Issue by 1e0ng** [JayYip/m3tl#27]
Hi, is this only for fine-tuning?
I see all examples are about fine-tuning.
Does it support pre-training? Any examples?

**Comment by JayYip** [comment]
You can see the example [here](https://github.com/JayYip/bert-multitask-learning/blob/9fe97739194f801e539efbadbaaf97a9c945eaaa/bert_multitask_learning/data_preprocessing/test_data.py#L54).
