### ISSUE TITLE
maybe a error in model_fn

### ISSUE THREAD

**Issue by YFwang1992** [JayYip/m3tl#4]
in model_fn.py line 284:
train_op = optimizer.apply_gradients(
            zip(grads, tvars), global_step=global_step)
but there is no apply_gradients in optimizer.py

**Comment by JayYip** [comment]
`apply_gradients` method is implemented in `tensorflow.python.training.optimizer.Optimizer`. 

I will close this issue since this is not a bug. Thanks.
