### ISSUE TITLE
make_hidden_model()调用时参数传递错误？

### ISSUE THREAD

**Issue by nefujiangping** [JayYip/m3tl#43]
[top.py](https://github.com/JayYip/bert-multitask-learning/blob/master/bert_multitask_learning/top.py) 中有两处([link1](https://github.com/JayYip/bert-multitask-learning/blob/1e1e12a0d0e77b4a77cbb0d7a1ea46199e37e6be/bert_multitask_learning/top.py#L138), [link2](https://github.com/JayYip/bert-multitask-learning/blob/1e1e12a0d0e77b4a77cbb0d7a1ea46199e37e6be/bert_multitask_learning/top.py#L479))调用函数`make_hidden_model()`时传递的最后一个参数似乎有问题，函数定义最后一个参数是bool类型的`is_seq`，而调用时传入的`'pooled'`字符串，会被解析为`True`

**Comment by JayYip** [comment]
这里是因为是这样判断的: [`if self.params.hidden_gru and is_seq:`](https://github.com/JayYip/bert-multitask-learning/blob/1e1e12a0d0e77b4a77cbb0d7a1ea46199e37e6be/bert_multitask_learning/top_utils.py#L80). 需要传入`False`, `None`或者空字符, 列表等, 才会被解析为`False`.
