### ISSUE TITLE
请问您的项目支持tf1.15吗？

### ISSUE THREAD

**Issue by kFoodie** [JayYip/m3tl#56]
您好，非常感谢您的分享。
我在使用您的项目的时候，发现tensor2tensor好像只支持tf2.2以上，然后看您的项目里面又是支持tf1.13；我装了tf1.15之后，运行您demo里面的代码，报了错

>   File "/root/data/glusterfs_sharing_04_v3/11117720/bert-multitask-learning-master/bert_multitask_learning/run_bert_multitask.py", line 120, in train_bert_multitask
    input_fn=train_input_fn, max_steps=params.train_steps, hooks=[train_hook])
  File "/root/miniconda3/envs/tf1.15/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 163, in __new__
    'Must specify max_steps > 0, given: {}'.format(max_steps))
ValueError: Must specify max_steps > 0, given: 0

使用的是这个代码 [https://github.com/JayYip/bert-multitask-learning/blob/master/notebooks/Run%20Pre-defined%20problems.ipynb](https://github.com/JayYip/bert-multitask-learning/blob/master/notebooks/Run%20Pre-defined%20problems.ipynb)
希望您能帮忙解答一下，万分感谢

**Comment by kFoodie** [comment]
您的项目中使用了tensorflow.contrib，然后相关依赖使用了tf2.2.0，最后会报No module named 'tensorflow.contrib'。。

**Comment by kFoodie** [comment]
https://github.com/JayYip/bert-multitask-learning/blob/master/notebooks/Run%20Pre-defined%20problems.ipynb
这里的代码跑通了，但是预测出来为空。。

**Comment by kFoodie** [comment]
`

def pred_wrappter(params, problem, estimator):
    try:
        text, label_data, label_encoder = params.read_data_fn[problem](
            params, PREDICT)
        data_list = zip(text, label_data)
    except ValueError:
        data_list, label_encoder = params.read_data_fn[problem](
            params, PREDICT)
    data_list, iter_for_pred = tee(data_list, 2)

    def pred_input_fn(): return predict_input_fn(
        iter_for_pred, params, mode=PREDICT, labels_in_input=True)
    pred_list = estimator.predict(pred_input_fn)
    return data_list, pred_list, label_encoder
`

`
data_list, iter_for_pred = tee(data_list, 2)
`
这一行返回为空。。
metrics.py 这个文件。。

**Comment by JayYip** [comment]
0.3.x支持1.15，但是现在安装比较麻烦... 需要自行确定tf1支持的t2t和dopamine-rl的版本

**Comment by JayYip** [comment]
> 您的项目中使用了tensorflow.contrib，然后相关依赖使用了tf2.2.0，最后会报No module named 'tensorflow.contrib'。。

是，部分代码尚未完全迁移，用到contrib模块主要是crf和`export_model.py`

**Comment by kFoodie** [comment]
感谢您的回复

**Comment by kFoodie** [comment]
现在您的代码在tf2.2.0上是可以正常使用了吗？

**Comment by JayYip** [comment]
是的，不过notebook还没有更新

**Comment by kFoodie** [comment]
难怪我这里一直报错……期待您的更新

**Comment by JayYip** [comment]
嗯，我之后会更新下notebook

**Comment by JayYip** [comment]
训练预定义problem的notebook已经更新：https://github.com/JayYip/bert-multitask-learning/blob/master/notebooks/Run%20Pre-defined%20problems.ipynb
