### ISSUE TITLE
How to modify optimization.py of original BERT code to implement multi GPU training? 

### ISSUE THREAD

**Issue by owen-chenhn** [JayYip/m3tl#6]
Hello! I am working on training BERT on multiple GPUs these days (using official code released by Google Research) and after specifying the Run_Config of the estimator with MirroredStrategy, I encountered an "ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context." This error was the same with that in [https://github.com/tensorflow/tensorflow/issues/23986#issuecomment-444389363](url) and I found your reply below. You said "You can take my implementation as a reference:", and therefore I came to this repo. 
I modified the original optimization.py code with reference to your src/optimizer.py but still got the same error, could you give me some advice about how to re-implement the optimizer in original optimization.py? 
The original official code of optimization.py is here [https://github.com/google-research/bert/blob/master/optimization.py](url)

**Comment by JayYip** [comment]
Hi, I did not have the same error. If you want to implement by yourself, you just need to implement `_apply_dense` and `_resource_apply_dense`. You can take the original Adam for reference. 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/adam.py

**Comment by owen-chenhn** [comment]
Do I need to modify `apply_gradients` of AdamWeightDecayOptimizer in optimization.py?

**Comment by JayYip** [comment]
No need.

**Comment by JayYip** [comment]
Closing the issue since this is not likely a bug.

**Comment by nlp4whp** [comment]
> Do I need to modify `apply_gradients` of AdamWeightDecayOptimizer in optimization.py?

sorry to bother you, does it works for you?

**Comment by JayYip** [comment]
> > Do I need to modify `apply_gradients` of AdamWeightDecayOptimizer in optimization.py?
> 
> sorry to bother you, does it works for you?

Are you having issues using the optimizer?

**Comment by nlp4whp** [comment]
> > > Do I need to modify `apply_gradients` of AdamWeightDecayOptimizer in optimization.py?
> > 
> > 
> > sorry to bother you, does it works for you?
> 
> Are you having issues using the optimizer?

oh yes, thanks. 

I also wanna modify optimization.py of BERT but not sure how to re-implement `_resource_apply_dense ` and `_apply_dense `.

now I just copy your implementation of `AdamWeightDecayOptimizer` but get the same error
```
ValueError: You must specify an aggregation method to update a MirroredVariable in Tower Context.
```

could you please give me some advise ?

**Comment by JayYip** [comment]
I did not encounter similar issues. My advise would be replace the optimizer with the standard Adam and try whether the issue still persist. If so, you can print out vars to find which one is not specified aggregation method. 

Please consider re-open the issue if you are confident that there's a bug in optimizer!

**Comment by nlp4whp** [comment]
> I did not encounter similar issues. My advise would be replace the optimizer with the standard Adam and try whether the issue still persist. If so, you can print out vars to find which one is not specified aggregation method.
> 
> Please consider re-open the issue if you are confident that there's a bug in optimizer!

Thanks again, both do not works for me, but I think yours is right.
I guess it might be about tf version, mine is 1.10.0. 
have you run it on tensorflow lower than 1.13.0 ?

**Comment by JayYip** [comment]
Nope. I tried on tf1.12 and 1.13.

**Comment by nlp4whp** [comment]
> Nope. I tried on tf1.12 and 1.13.

yeah it works on tf1.12 !! you did me a big favor!

**Comment by jiahuigeng** [comment]
> > Nope. I tried on tf1.12 and 1.13.
> 
> yeah it works on tf1.12 !! you did me a big favor!

Could you please share your implementation for multi-gpu training? I met the same problem but using tf1.12 doesn't work. sad..

**Comment by nlp4whp** [comment]
> > > Nope. I tried on tf1.12 and 1.13.
> > 
> > 
> > yeah it works on tf1.12 !! you did me a big favor!
> 
> Could you please share your implementation for multi-gpu training? I met the same problem but using tf1.12 doesn't work. sad..

ok
Basically, I just replaced `AdamWeightDecayOptimizer`  in BERT with the same class in this repo.

**Comment by nlp4whp** [comment]
ok, here's mine
