### ISSUE TITLE
notebook is not working

### ISSUE THREAD

**Issue by wolyosung** [JayYip/m3tl#78]
I think your patch made notebook files not working such as Run Self Defined Problem with Modified Model.ipynb.
it tries to import create_single_problem_generator, which does not exist anymore..
can you fix it?

**Comment by JayYip** [comment]
Sure, I'll fix it ASAP. But modified model is not currently supported after switching to keras api. I'll fix the other two notebooks first and add modifying model support back later. Shouldn't be too difficult.

**Comment by JayYip** [comment]
Notebooks are updated. I'll close the issue. If you need modified model to work, please raise another issue. Thanks!

**Comment by wolyosung** [comment]
thank you very much!
